
import { Category, VocabularyWord } from './types';

export const CATEGORIES: Category[] = [
  { name: 'Literature', emoji: '📚', color: 'bg-white', textColor: 'text-gray-900' },
  { name: 'Science', emoji: '🔬', color: 'bg-white', textColor: 'text-gray-900' },
  { name: 'Travel', emoji: '🌍', color: 'bg-white', textColor: 'text-gray-900' },
  { name: 'Work', emoji: '💼', color: 'bg-white', textColor: 'text-gray-900' },
  { name: 'Emotions', emoji: '❤️', color: 'bg-white', textColor: 'text-gray-900' },
  { name: 'Food', emoji: '👨‍🍳', color: 'bg-white', textColor: 'text-gray-900' },
  { name: 'Social', emoji: '💬', color: 'bg-white', textColor: 'text-gray-900' },
  { name: 'Time', emoji: '⏰', color: 'bg-white', textColor: 'text-gray-900' },
  { name: 'Art', emoji: '🎨', color: 'bg-white', textColor: 'text-gray-900' },
  { name: 'Finance', emoji: '💰', color: 'bg-white', textColor: 'text-gray-900' },
];

export const CATEGORIES_B1: Category[] = [
  { name: 'Travel & Holidays', emoji: '✈️', color: 'bg-white', textColor: 'text-gray-900' },
  { name: 'Work & Study', emoji: '📝', color: 'bg-white', textColor: 'text-gray-900' },
  { name: 'Social Life', emoji: '🥂', color: 'bg-white', textColor: 'text-gray-900' },
  { name: 'Health', emoji: '🏥', color: 'bg-white', textColor: 'text-gray-900' },
  { name: 'Shopping', emoji: '🛍️', color: 'bg-white', textColor: 'text-gray-900' },
  { name: 'Food & Restaurants', emoji: '🍽️', color: 'bg-white', textColor: 'text-gray-900' },
  { name: 'Environment', emoji: '🌳', color: 'bg-white', textColor: 'text-gray-900' },
  { name: 'Technology', emoji: '💻', color: 'bg-white', textColor: 'text-gray-900' },
  { name: 'Culture', emoji: '🎭', color: 'bg-white', textColor: 'text-gray-900' },
  { name: 'Opinions & Emotions', emoji: '🤔', color: 'bg-white', textColor: 'text-gray-900' },
];

// Mapping old data keys to new category names
const DATA_MAPPING = {
  'Travel & Tourism': 'Travel',
  'Food & Dining': 'Food',
  'Education & Classroom': 'Literature',
  'Workplace & Office': 'Work',
  'Home & Household': 'Art', // Best available slot for unused data, though imperfect
  'Shopping & Money': 'Finance',
  'Health & Body': 'Science', // Best available slot
  'Time & Weather': 'Time',
  'Feelings & Personality': 'Emotions',
  'People & Social Life': 'Social',
};

const RAW_VOCABULARY_DATA: Record<string, VocabularyWord[]> = {
  'Travel & Tourism': [
    { word: "arrive (v.)", definition: "to reach a place", example: "We arrived at the hotel late at night." },
    { word: "depart (v.)", definition: "to leave a place", example: "The train departs at 8:30 a.m." },
    { word: "destination (n.)", definition: "the place you are going to", example: "Our destination is London." },
    { word: "luggage (n.)", definition: "bags or suitcases used for travel", example: "Her luggage was very heavy." },
    { word: "passport (n.)", definition: "a document needed for international travel", example: "Don’t forget your passport at home!" },
    { word: "ticket (n.)", definition: "a piece of paper that allows travel", example: "I bought a plane ticket online." },
    { word: "boarding pass (n.)", definition: "a card that lets you get on a plane", example: "Please show your boarding pass at the gate." },
    { word: "flight (n.)", definition: "a journey on an airplane", example: "Our flight was delayed for two hours." },
    { word: "pilot (n.)", definition: "a person who flies an airplane", example: "The pilot announced our arrival time." },
    { word: "airline (n.)", definition: "a company that runs airplane services", example: "She works for a famous airline." },
    { word: "tourist (n.)", definition: "a person who travels for pleasure", example: "Tourists love visiting the old temples." },
    { word: "hotel (n.)", definition: "a building where travelers can stay", example: "We booked a hotel near the beach." },
    { word: "reservation (n.)", definition: "an arrangement to have a room or seat", example: "I made a reservation at a nice restaurant." },
    { word: "guide (n.)", definition: "a person who shows places to visitors", example: "Our guide explained the city’s history." },
    { word: "map (n.)", definition: "a picture that shows roads and places", example: "He looked at the map to find the museum." },
    { word: "bus stop (n.)", definition: "a place where buses stop", example: "We waited at the bus stop for 10 minutes." },
    { word: "taxi (n.)", definition: "a car that takes passengers for money", example: "We took a taxi to the station." },
    { word: "train (n.)", definition: "a long vehicle that runs on rails", example: "The train was crowded this morning." },
    { word: "subway (n.)", definition: "an underground train", example: "The subway is fast and convenient." },
    { word: "ticket counter (n.)", definition: "a place where you buy tickets", example: "Go to the ticket counter to get your pass." },
    { word: "platform (n.)", definition: "the area beside train tracks", example: "The train left from platform 4." },
    { word: "schedule (n.)", definition: "a plan showing times", example: "Our travel schedule is very busy." },
    { word: "route (n.)", definition: "the path to get somewhere", example: "We took the fastest route to the airport." },
    { word: "journey (n.)", definition: "the act of traveling from one place to another", example: "It was a long journey across the country." },
    { word: "fare (n.)", definition: "the money you pay for a trip", example: "The bus fare has gone up this year." },
    { word: "customs (n.)", definition: "the place where bags are checked at the airport", example: "We passed through customs quickly." },
    { word: "visa (n.)", definition: "a document that allows entry to another country", example: "You need a visa to study abroad." },
    { word: "tour (n.)", definition: "a planned trip to see interesting places", example: "We joined a city tour in Bangkok." },
    { word: "adventure (n.)", definition: "an exciting experience", example: "Climbing the mountain was a great adventure." },
    { word: "explore (v.)", definition: "to travel around and learn about new places", example: "We explored the city on foot." },
    { word: "compass (n.)", definition: "a tool showing directions", example: "The explorer used a compass to find north." },
    { word: "north (n.)", definition: "the direction opposite south", example: "Canada is north of the United States." },
    { word: "south (n.)", definition: "the direction opposite north", example: "They drove south toward the sea." },
    { word: "east (n.)", definition: "the direction where the sun rises", example: "Japan is to the east of China." },
    { word: "west (n.)", definition: "the direction where the sun sets", example: "The sun goes down in the west." },
    { word: "border (n.)", definition: "a line separating two countries", example: "They crossed the border into Thailand." },
    { word: "road (n.)", definition: "a path for vehicles", example: "The road was wet after the rain." },
    { word: "highway (n.)", definition: "a main road for long-distance travel", example: "We drove along the highway to the city." },
    { word: "bridge (n.)", definition: "a structure for crossing over water or roads", example: "The bridge connects two towns." },
    { word: "crosswalk (n.)", definition: "a place for people to cross the street", example: "Use the crosswalk when the light is green." },
    { word: "traffic (n.)", definition: "the movement of vehicles", example: "The traffic was terrible this morning." },
    { word: "accident (n.)", definition: "something bad that happens suddenly", example: "There was a car accident near the station." },
    { word: "driver (n.)", definition: "a person who operates a vehicle", example: "The taxi driver was very friendly." },
    { word: "license (n.)", definition: "an official card that allows driving", example: "You need a license to drive a car." },
    { word: "petrol (n.)", definition: "fuel for cars", example: "The car ran out of petrol." },
    { word: "rent (v.)", definition: "to pay for temporary use", example: "We rented a car for our trip." },
    { word: "speed (n.)", definition: "how fast something moves", example: "The car was driving at high speed." },
    { word: "seat belt (n.)", definition: "a safety strap in a car", example: "Fasten your seat belt before driving." },
    { word: "stop (v.)", definition: "to bring to a halt", example: "The bus stopped at the next corner." },
    { word: "turn (v.)", definition: "to change direction", example: "Turn left at the traffic light." },
    { word: "direction (n.)", definition: "the way something moves or faces", example: "Can you give me directions to the bank?" },
    { word: "station (n.)", definition: "a place where buses or trains stop", example: "We met at the train station." },
    { word: "delay (n.)", definition: "a wait caused by problems", example: "The flight had a two-hour delay." },
    { word: "arrangement (n.)", definition: "a plan made in advance", example: "We made travel arrangements early." },
    { word: "travel agency (n.)", definition: "a company that organizes trips", example: "We booked our tour at a travel agency." },
    { word: "cruise (n.)", definition: "a trip on a large ship for pleasure", example: "They went on a Caribbean cruise." },
    { word: "ship (n.)", definition: "a large boat for traveling on water", example: "The ship sailed across the ocean." },
    { word: "boat (n.)", definition: "a small water vehicle", example: "We crossed the river by boat." },
    { word: "harbor (n.)", definition: "a place where ships stop", example: "The harbor was full of fishing boats." },
    { word: "sail (v.)", definition: "to travel on water using wind", example: "We sailed along the coast." },
    { word: "island (n.)", definition: "land surrounded by water", example: "They spent their holiday on a small island." },
    { word: "coast (n.)", definition: "land next to the sea", example: "We walked along the coast at sunset." },
    { word: "mountain (n.)", definition: "a very high hill", example: "We climbed the mountain in two days." },
    { word: "valley (n.)", definition: "a low area between hills", example: "The village lies in a green valley." },
    { word: "lake (n.)", definition: "a large body of water", example: "They went fishing at the lake." },
    { word: "river (n.)", definition: "a large natural flow of water", example: "The river runs through the city." },
    { word: "ocean (n.)", definition: "the huge saltwater body covering the Earth", example: "We saw dolphins in the ocean." },
    { word: "shore (n.)", definition: "the land beside a body of water", example: "Children played on the shore." },
    { word: "beach (n.)", definition: "sandy area by the sea", example: "We built sandcastles on the beach." },
    { word: "camp (n.)", definition: "a place for staying outdoors", example: "We stayed at a mountain camp." },
    { word: "tent (n.)", definition: "cloth shelter used outdoors", example: "We slept in a tent during the trip." },
    { word: "backpack (n.)", definition: "a bag carried on the back", example: "She packed her clothes in a backpack." },
    { word: "camera (n.)", definition: "a device for taking photos", example: "Don’t forget your camera!" },
    { word: "photo (n.)", definition: "a picture taken with a camera", example: "We took many photos on our trip." },
    { word: "souvenir (n.)", definition: "something kept to remember a place", example: "He bought a souvenir from Paris." },
    { word: "plan (n.)", definition: "a detailed idea of what to do", example: "Our travel plan includes five cities." },
    { word: "budget (n.)", definition: "a plan for spending money", example: "We traveled on a small budget." },
    { word: "local (adj.)", definition: "belonging to a particular place", example: "We ate at a local restaurant." },
    { word: "foreign (adj.)", definition: "from another country", example: "He likes learning foreign languages." },
    { word: "currency (n.)", definition: "the money of a country", example: "What is the currency in Japan?" },
    { word: "exchange (v.)", definition: "to trade money or goods", example: "We exchanged dollars for euros." },
    { word: "airport (n.)", definition: "a place where planes take off and land", example: "The airport was very busy today." },
    { word: "gate (n.)", definition: "the area where passengers board a plane", example: "Please go to gate number 12." },
    { word: "terminal (n.)", definition: "a building for passengers at an airport", example: "We arrived at the international terminal." },
    { word: "baggage claim (n.)", definition: "area where you collect luggage", example: "We waited at the baggage claim area." },
    { word: "security check (n.)", definition: "inspection before boarding", example: "We went through the security check." },
    { word: "arrival (n.)", definition: "the act of coming to a place", example: "We celebrated their safe arrival." },
    { word: "departure (n.)", definition: "the act of leaving", example: "The departure gate is on the right." },
    { word: "flight attendant (n.)", definition: "person who serves passengers on a plane", example: "The flight attendant offered drinks." },
    { word: "seat (n.)", definition: "a place to sit", example: "I prefer a window seat." },
    { word: "window (n.)", definition: "glass opening to look outside", example: "The view from the window was amazing." },
    { word: "aisle (n.)", definition: "a walkway between seats", example: "He sat on the aisle seat." },
    { word: "land (v.)", definition: "to come down from the air", example: "The plane landed safely." },
    { word: "take off (v.)", definition: "to leave the ground", example: "The plane took off on time." },
    { word: "travel (v.)", definition: "to go from one place to another", example: "We love to travel together." },
    { word: "explorer (n.)", definition: "a person who travels to discover new places", example: "Old explorers discovered new lands." },
    { word: "trip (n.)", definition: "a short journey", example: "We had a wonderful weekend trip." },
    { word: "itinerary (n.)", definition: "a detailed plan for a journey", example: "Our travel agent sent us the final itinerary for our trip." },
    { word: "hostel (n.)", definition: "an inexpensive lodging place for travelers", example: "We stayed in a youth hostel to save money during our trip." },
    { word: "resort (n.)", definition: "a place where people go for vacation and relaxation", example: "They spent a week at a luxury beach resort." },
  ],
  // ... (Other categories remain, data will be mapped dynamically or fetched)
};

// Rebuild VOCABULARY_DATA with new keys and potentially migrated content
// Note: B1 Categories currently map to empty arrays or recycled data to prevent crashes
// In a real app, you would populate RAW_VOCABULARY_DATA with B1 content.
export const VOCABULARY_DATA: Record<string, VocabularyWord[]> = Object.fromEntries(
  Object.entries(RAW_VOCABULARY_DATA).map(([key, value]) => {
    // @ts-ignore
    const newKey = DATA_MAPPING[key] || key; // Use key if no mapping found
    return [newKey, value];
  })
);
